repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
        - id: pyupgrade

-   repo: https://github.com/python-poetry/poetry
    rev: 1.2.2  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]

-   repo: local
    hooks:
      - id: docs
        name: mkdocs
        entry: bash -c 'mkdocs gh-deploy'
        language: system
