language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
# command to run tests
script:
  - python -m pytest --cov=design tests/
  - python -m pytest --cov=simulation tests/test_ngspice_warper.py
