language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
# command to run tests
script:
# command to run tests
- python -m pytest --cov-report term-missing:skip-covered --cov=passive_auto_design

deploy:
  provider: pypi
  user: Patarimi
  skip_cleanup: true
  password:
    secure: cMjr2aUjeord6msxGfcS5rXw3Xro1l0M2YTcX54uOwuUIIR/OeWoz4JOeUZ7nGVCWuEMp3XGwWOy4nN2Sx4rV6IEUc+HdNrBqN2aWJt/1hglFYPod6PsVlcZLwLQxK94frtB40mkLnKewt/sre5OPOCtwzz5UaFpRuIEPJgzejnXtqIMP+zUK7S07nCU3ibJqTAcLiOA9PZ8jnT1be5eK6W1mbfIh9Lm+1347wqXTP3ow2iE2SvhcMMuX6/7w1Wv9+rsf8Tjx1z8gFaNvNEQZJmsa1/xqKwI4Kfsgl5JGSNUNY10jhcn3ip9gFcq6p2qW0gFlANAA/6bjkliYLEF1o61pOZJpSuSF+10E11JDxqXWTwFksdVDC8abZ+oKLWSHf+p7E8n1gpTFZmFVUbrSSjmsqbKxYaeS+pbRnJoQM+ZQetm745ASIGxk9i9zIzE9P6T1U2EGAqZr+qaCDk9uvhbqAR6H1gwDDuEDpQxEuHFOYLyp6YV+6PStZevZ4uz+/w3pJUBXcZPQal2xe/0bhO9pcMPlpLgHH5HzGz8MOtzM5j4CWITEhEVejyemHoctWhFunnwLO0aoOClYWo0jpsVRjntgUCVxCP7eKoIok6tgFoU7fXJBs+KPl4Bp0GXU7LRzY5QbeBwuwHSvl83t7Te/enzYSUrTjGr+ajhCgQ=
