# appveyor.yml
---
environment:
  global:
    PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7.x"
    PYTHON_ARCH: "64"

build: off

install:
- set PATH=%PYTHON%\\scripts;%PATH%
- pip install -qr --no-warn-script-location requirements.txt
- pip install -q  --no-warn-script-location pytest-cov
- cd ..
- ps: Start-FileDownload https://netix.dl.sourceforge.net/project/ngspice/ng-spice-rework/30/ngspice-30_64.zip
- 7z e ngspice-30_64.zip -aoa
- dir /b
- Rename ngspice-30_64 ngspice

test_script:
- "%PYTHON%\\python.exe -m pytest --cov-report term-missing:skip-covered --cov=passive_auto_design"
