# appveyor.yml
---
environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310-x64"

build: false

install:
- set PATH=%PYTHON%\\scripts;%PATH%
# install poetry
- "curl -sSL https://install.python-poetry.org | %PYTHON%\\python.exe -"
- "SET PATH=%USERPROFILE%\\.poetry\\bin;%PATH%"

# install package
- "poetry install -v"


test_script:
  - "poetry run pytest -v --terminate tests"
