# appveyor.yml
---
environment:
  PYPIPASSWORD:
    secure: Z5wNxGEgsd3z+VoLXHUDkA==

  global:
    PYTHON: "C:\\Python38-x64"
    PYTHON_VERSION: "3.8.x"
    PYTHON_ARCH: "64"

build: false

install:
- set PATH=%PYTHON%\\scripts;%PATH%
- "%PYTHON%\\python.exe -m pip install --upgrade pip"
- pip install -qr requirements.txt
- pip install -q pytest-cov

test_script:
- cd C:\projects\passiveautodesign
- "%PYTHON%\\python.exe -m pytest --cov-report term-missing:skip-covered --cov=passive_auto_design"
