# appveyor.yml
---
environment:
  global:
    PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7.x"
    PYTHON_ARCH: "64"

build: off

install:
- set PATH=%PYTHON%\\scripts;%PATH%
- pip install -r requirements.txt
- pip install pytest-cov

test_script:
- "%PYTHON%\\python.exe -m pytest --cov-report term-missing:skip-covered --cov=passive_auto_design"
