# appveyor.yml
---
environment:
  global:
    PYTHON: "C:\\Python36-x64"

build: off

install:
- "%PYTHON%\\python.exe -m pip install --upgrade pip"
- pip install -r requirements.txt
- pip install pytest-cov

test_script:
- "%PYTHON%\\python.exe -m pytest --cov-report term-missing:skip-covered --cov=passive_auto_design"
