# appveyor.yml
---
environment:
  matrix:
    - TOXENV: py39
    - TOXENV: py310

build: false

install:
# install poetry
- curl -sSL https://install.python-poetry.org | py -
- "SET PATH=C:\\Users\\appveyor\\AppData\\Roaming\\Python\\Scripts;%PATH%"

# install package
- "poetry install -v"


test_script:
  - "poetry run pytest -v --terminate tests"
