# appveyor.yml
---
environment:
  PYPIPASSWORD:
    secure: Z5wNxGEgsd3z+VoLXHUDkA==

  global:
    PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7.x"
    PYTHON_ARCH: "64"

build: off

install:
- set PATH=%PYTHON%\\scripts;%PATH%
- pip install -qr requirements.txt --no-warn-script-location
- pip install -q pytest-cov --no-warn-script-location
- cd ..
- mkdir ng_spice
- cd ng_spice
- ps: Start-FileDownload https://netix.dl.sourceforge.net/project/ngspice/ng-spice-rework/30/ngspice-30_64.zip
- 7z e ngspice-30_64.zip -aoa

test_script:
- cd C:\projects\passiveautodesign
- "%PYTHON%\\python.exe -m pytest --cov-report term-missing:skip-covered --cov=passive_auto_design"

deploy_script:
    # Specify account details for PyPI
      - echo [distutils]                                  > %USERPROFILE%\\.pypirc
      - echo index-servers =                             >> %USERPROFILE%\\.pypirc
      - echo     pypi                                    >> %USERPROFILE%\\.pypirc
      - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
      - echo username=Patarimi                            >> %USERPROFILE%\\.pypirc
      - echo password=%PYPIPASSWORD%                     >> %USERPROFILE%\\.pypirc
  
    # Workaround required to ensure setup.py finds the .pypirc under Windows
      - set HOME=%USERPROFILE%

      - pip install -q --user --upgrade setuptools wheel twine --no-warn-script-location
      - "%PYTHON%\\python.exe setup.py -q sdist bdist_wheel"
      - "%PYTHON%\\python.exe -qm twine upload dist/* --skip-existing"
