# appveyor.yml
---
image:
  - Visual Studio 2019

environment:
  matrix:
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310

build: false

install:
# install tox
- py -m pip install tox

test_script:
- py -m tox
