site_name: PassiveAutoDesign
site_url: https://patarimi.github.io/PassiveAutoDesign/
repo_url: https://github.com/Patarimi/PassiveAutoDesign


nav:
  - Home: README.md
  - Code Reference: reference/

theme: material

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      watch:
        - passive_auto_design
      handlers:
        python:
          selection:
            docstring_style: numpy
