site_name: PassiveAutoDesign
site_url: https://passiveautodesign.netlify.app/
repo_url: https://github.com/Patarimi/PassiveAutoDesign


nav:
  - Home: index.md
  - Code Reference:
      - Special: special.md
      - Space Mapping: spacemap.md
      - Components:
          - Lumped Element: components/lumped_element.md
          - Taper: components/taper.md
          - Transformer: components/transformer.md
          - Waveguide: components/waveguide.md
      - Devices:
          - Balun: devices/balun.md
          - Coupler: devices/coupler.md
      - Examples:
          - Substrate: examples/example_substrate.py
          - Balun: examples/example_balun_sizing.py
          - Coupler: examples/example_coupler_sizing.py
          - Taper: examples/example_taper_sizing.py
          - Waveguide: examples/example_waveguide_sizing.py
          - Space Mapping: examples/example_space_mapping.py

theme: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
  - mkdocs-jupyter